// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH8k59pnuWft0k8R0y32iQexcS2IHv-Ak',
    appId: '1:583349974038:web:80d134879552052f753137',
    messagingSenderId: '583349974038',
    projectId: 'sanserveall-mobile',
    authDomain: 'sanserveall-mobile.firebaseapp.com',
    storageBucket: 'sanserveall-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjgVBc3BtnfQHo4NnCfxEPbpuFiHGZC7M',
    appId: '1:583349974038:android:657fb9ee2ce4f421753137',
    messagingSenderId: '583349974038',
    projectId: 'sanserveall-mobile',
    storageBucket: 'sanserveall-mobile.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ3z1Wk7WMzHJG0mCqT4gjpPLIQeEKRtI',
    appId: '1:583349974038:ios:9cca4e03726ffb49753137',
    messagingSenderId: '583349974038',
    projectId: 'sanserveall-mobile',
    storageBucket: 'sanserveall-mobile.firebasestorage.app',
    iosBundleId: 'com.example.sanserveallMobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ3z1Wk7WMzHJG0mCqT4gjpPLIQeEKRtI',
    appId: '1:583349974038:ios:9cca4e03726ffb49753137',
    messagingSenderId: '583349974038',
    projectId: 'sanserveall-mobile',
    storageBucket: 'sanserveall-mobile.firebasestorage.app',
    iosBundleId: 'com.example.sanserveallMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH8k59pnuWft0k8R0y32iQexcS2IHv-Ak',
    appId: '1:583349974038:web:0a37a1cfa4aad4e8753137',
    messagingSenderId: '583349974038',
    projectId: 'sanserveall-mobile',
    authDomain: 'sanserveall-mobile.firebaseapp.com',
    storageBucket: 'sanserveall-mobile.firebasestorage.app',
  );
}
